version: "3"
services:
  translate:
    image: python:3.10.6
    environment:
      - PIP_INDEX_URL=https://pypi.tuna.tsinghua.edu.cn/simple
    ports:
      - 9877:9877
    working_dir: /home/translateService
    volumes:
      - ./:/home/translateService
    command: /home/translateService/start.sh 172.17.0.1:10086
    restart: always
